services:
  users_service:
    tty: true
    stdin_open: true
    build:
      context: ./users_service
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    depends_on:
      - users_db
    volumes:
      - ./users_service:/app
      - bundle_cache:/usr/local/bundle

  users_db:
    image: postgres:13
    environment:
      POSTGRES_DB: users_service_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - users_db_data:/var/lib/postgresql/data

  products_service:
    tty: true
    stdin_open: true
    build:
      context: ./products_service
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    depends_on:
      - products_db
    volumes:
      - ./products_service:/app
      - bundle_cache:/usr/local/bundle

  products_db:
    image: postgres:13
    environment:
      POSTGRES_DB: products_service_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - products_db_data:/var/lib/postgresql/data

  orders_service:
    tty: true
    stdin_open: true
    build:
      context: ./orders_service
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3000"
    depends_on:
      - orders_db
    volumes:
      - ./orders_service:/app
      - bundle_cache:/usr/local/bundle

  orders_db:
    image: postgres:13
    environment:
      POSTGRES_DB: orders_service_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - orders_db_data:/var/lib/postgresql/data

  notifications_service:
    tty: true
    stdin_open: true
    build:
      context: ./notifications_service
      dockerfile: Dockerfile.dev
    ports:
      - "3004:3000"
    depends_on:
      - notifications_db
    volumes:
      - ./notifications_service:/app
      - bundle_cache:/usr/local/bundle

  notifications_db:
    image: postgres:13
    environment:
      POSTGRES_DB: notifications_service_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - notifications_db_data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge

volumes:
  users_db_data:
  products_db_data:
  orders_db_data:
  notifications_db_data:
  bundle_cache:
